### ISSUE TITLE
 Tapping the map while in follow mode stops following the location

### ISSUE THREAD

**Issue by dpalacio** [hauke96/GeoNotes#26] opened 2021-02-10 22:44 UTC
The follow mode is enabled by clicking the second button from the right in the top bar. It will center the device location in the map continuously. Once you tap anywhere in the map to create a note, this mode is lost.

The tooltip for this button says "Settings", by the way. You can check it by holding tap over the button.

**Comment by hauke96** [comment] 2021-02-10 23:04
Disabling the follow mode after tapping on the map is intentional. But I think this is more or less a duplicate of #27 isn't it? Therefore I'll focus on the other ticket.

However thanks for the hint on the tooltip :+1:

**Closed by hauke96** 2021-02-10 23:04 UTC
