### ISSUE TITLE
Collections of notes

### ISSUE THREAD

**Issue by dpalacio** [hauke96/GeoNotes#21] opened 2021-02-07 21:27 UTC
Please implement collections or lists of notes. It would enable us to:

1. List existing notes
2. Categorize notes
3. Manage notes
4. Delete lists of notes

**Comment by hauke96** [comment] 2021-02-07 23:27
Hi,

thanks for this feature request. There are some questions I have regarding your points:

1. List existing notes: Probably is a duplicate of #13
2. Categorize notes: So like for GitHub issues you want to add custom labels to a note?
3. Manage notes: What exactly does "manage" mean? What actions does "manage" involve?
4. Delete lists of notes: You speak of "lists" (plural), so there are multiple lists of notes. Where do they come from? How would you like to create those lists?

**Comment by dpalacio** [comment] 2021-02-07 23:36
1. Yes, it's partially a duplicate but it's got more to it
2. Yes, so that I can check the notes by town or tasks
3. Besides deletion of lists, reordering
4. I would create a list for many reasons: surveying the town to add POIs to OpenStreetMap; surveying a different area; keeping track of sessions/days of tagging so that I can delete the notes I made yesterday and already added to OSM; tagging personal items;

**Comment by hauke96** [comment] 2021-02-07 23:56
I think I now understand the basic concept of your idea. However this is a massive feature, so don't expect results soon. 

But I like your idea. A list is then basically a filtered version of the whole set of notes (filtered by date and/or label). I can also imagine to extend this filter idea to the map, so that you can filter the notes on the map by date, label or list. Something like that, but I think this is a feature for the far future :D

**Comment by mondlicht-und-sterne** [comment] 2021-02-11 17:26
> Please implement collections or lists of notes. It would enable us to:
> 
> 1. List existing notes
> 2. Categorize notes
> 3. Manage notes
> 4. Delete lists of notes

that's exactly what I meant, and if you click on the note, is that where you are on the app?

**Comment by mondlicht-und-sterne** [comment] 2021-02-11 17:28
> > Please implement collections or lists of notes. It would enable us to:
> > 
> > 1. List existing notes
> > 2. Categorize notes
> > 3. Manage notes
> > 4. Delete lists of notes
> 
> that's exactly what I meant, and if you click on the note, is that where you are on the app?

it doesn't matter when this can be changed, but that would be really helpful.

**Comment by opk12** [comment] 2021-07-03 11:27
I use another app with lists `to survey`, `surveyed and upstreamable`, `surveyed to review`.

On the map, each note has
- a color, to identify the list
- a symbol for the kind of POI, independent of the list and color

When I am on a route where I already took some POIs, I can recognize very fast (just by looking at the map) that a bus stop is ready for upstreaming, but the nearby waste basket is not noted or needs observation/survey, so I know which note to click for details. This makes it very fast to catch POIs while being driven by car or on the bus.

**Comment by hauke96** [comment] 2021-07-03 11:52
I assume with "POI" you mean notes in a map? However, coloring lists (and notes accordingly) sounds reasonable and doable. Thanks for the suggestion.

**Comment by opk12** [comment] 2021-07-03 12:49
> I assume with "POI" you mean notes in a map? However, coloring lists (and notes accordingly) sounds reasonable and doable. Thanks for the suggestion.

[Points of Interest](https://wiki.openstreetmap.org/wiki/Points_of_interest). I collect them on the phone and upload them later in an OpenStreetMap editor at home.

**Comment by barefootstache** [comment] 2022-05-10 18:45
Hey, I will try to tackle this feature. Though as mentioned it might take some time to develop.

One feature that I feel like is missing is the multi-select of notes and just delete them over deleting all of them at once.

**Comment by hauke96** [comment] 2022-05-10 23:40
Hi, @barefootstache thanks for the initiative. However I just continued working on this today (take a look on the [project page for 1.5.0](https://github.com/hauke96/GeoNotes/projects/4) to see the current status on issues). Feel free to share your ideas, mock-ups, etc. and I'm sorry if you already started to work on this, but I think it's not a good idea that we both work on this topic. I'll also assign myself to tickets I'm working on, this will hopefully prevent separate implementations and unnecessary work.

Your multi-select idea on the other hand is a good issue to work on. As far as I understand, it's completely separate from the categorization of notes, so there souldn't be any conflict with the stuff I'm working on. But please create a new issue if you start working on that, so that it's transparent for everyone who does what.

**Comment by barefootstache** [comment] 2022-05-15 21:17
> Hi, @barefootstache thanks for the initiative. However I just continued working on this today (take a look on the [project page for 1.5.0](https://github.com/hauke96/GeoNotes/projects/4) to see the current status on issues). Feel free to share your ideas, mock-ups, etc. and I'm sorry if you already started to work on this, but I think it's not a good idea that we both work on this topic. I'll also assign myself to tickets I'm working on, this will hopefully prevent separate implementations and unnecessary work.
> 
> Your multi-select idea on the other hand is a good issue to work on. As far as I understand, it's completely separate from the categorization of notes, so there souldn't be any conflict with the stuff I'm working on. But please create a new issue if you start working on that, so that it's transparent for everyone who does what.

Hey, sadly I commented before taking a look at the project page. Thus I didn't touch that point because having two branches for the same issue makes little sense. Good to know that my suggestion is a different issue and will make it shortly.

**Closed** 2022-10-18 21:04 UTC
Labels: enhancement
