### ISSUE TITLE
Selectable colours for map markers

### ISSUE THREAD

**Issue by cloudrac3r** [hauke96/GeoNotes#51] opened 2021-09-21 04:56 UTC
Hi there! First off, thanks for this great app, it's been so helpful for me when surveying data to add to the map.

I am requesting a feature. I would like the ability to add a different colour to some of the markers on the map. I am currently surveying a mall, and as you can see, I have a lot of markers. It is really really difficult to distinguish at a glance which are relevant to what I am currently doing.

Having different colours would be helpful to me. For example, I could use red for one floor of the mall and blue for another floor. These would help me to focus on what matters when I am trying to enter data into JOSM after I return home. Currently, trying to distinguish between floors is extremely difficult on a 2D map.

[Here's a screenshot of what my survey notes look like so far.](https://user-images.githubusercontent.com/28467304/134113182-c42699f6-52f4-411b-afeb-805a15a0509a.png) Most of these are on the ground floor, I haven't properly explored the other floors yet. Place names have been redacted for privacy.

A preset list of 8 different colours would be the best way. There's no need for a full RGB picker.

Here is what would be useful for me:

- A switch in settings which changes the default colour for new notes
- An option when clicking an existing note to change its colour
- Colours should be a property in the .geojson export so I can search & filter with them JOSM

I have experience with Java, but not with Android development, so I would not be able to implement this feature myself without some help.

**Comment by hauke96** [comment] 2021-09-21 13:48
Hi, I'm glad you use and like GeoNotes and also thanks for this feature request. However, maybe this is a duplicate of issue #21 (s. [this comment](https://github.com/hauke96/GeoNotes/issues/21#issuecomment-873395979))? That issue wants to categorize notes into lists, including coloring all the notes.

**Comment by cloudrac3r** [comment] 2021-09-21 14:00
There are definitely similarities between the issue threads, and it would make sense to implement them as the same feature! Thank you <3

**Comment by hauke96** [comment] 2021-09-21 14:12
Alright, I then close this issue (it's still linked in issue 21).

**Closed by hauke96** 2021-09-21 14:12 UTC
