### ISSUE TITLE
different colours for notes

### ISSUE THREAD

**Issue by legofahrrad** [hauke96/GeoNotes#73] opened 2022-05-08 14:17 UTC
I recently came across this app and love it. So, first of all, thank you very much!

I use the app in two ways:
1. creating notes when being outside to add something to OSM at home
2. creating notes at home to check things on-site

That's why I made some thoughts about different colours. I think it would be nice to have some sort of menu when creating a note to set a colour. So I can see a difference between the notes I have to check and the ones I created on the go.

Simple Mock-Up:
![mock-up](https://user-images.githubusercontent.com/92865620/167300302-96950a50-d8a1-416a-a479-ce3cac949540.jpg)
(There is a row with different colours and when clicking on one of them, the note gets this colour as background)

**Comment by hauke96** [comment] 2022-05-09 10:55
Hi, thanks for the feature request and the mock-up :)
This is basically a duplicate of #21 (there was some discussion but the base idea is to create categories for notes and assign colors to these categories), which will be implemented in the next major update in version 1.5.0. However my time is limited to don't expect results too soon ;)

Because this is basically a duplicate I'm going to close this but feel free to add comments in issue #21.

**Closed by hauke96** 2022-05-09 10:55 UTC
