### ISSUE TITLE
Text box too high

### ISSUE THREAD

**Issue by opk12** [hauke96/GeoNotes#36] opened 2021-07-03 12:50 UTC
The text box is high 6 lines, so the first 3 lines are not visible (are beyond the map's upper border) and typing seems not to have effect. To see what you typed, drag the map while the note is selected.

This is on a Samsung Galaxy J5 with Android 7.

**Comment by hauke96** [comment] 2021-07-03 13:00
Unfortunately it's not really possible to dynamically set the input size in respect tot the screen size or something like that, because it's a popup and the keyboard comes up etc.

For the person fixing this:
I think reducing the amount of lines to two would do the trick. Even better would be a settings entry to manually change the number of line for people wanting to have more or less lines.

**Comment by opk12** [comment] 2021-07-03 13:40
What about a border around the note's balloon, or another visual indication that the balloon extends beyond what you see? Before discovering this map scrolling "secret trick" by chance, I did believe the text box has white-on-white characters (as in the totally unrelated #35) and height of a couple of lines; and note editing was hard (the default Samsung keyboard lacks left/right arrows).

**Comment by hauke96** [comment] 2021-07-03 14:29
The problem is, that the popup/balloon is embedded within the map, so that it moves with the map (which I wouldn't change). Positioning and dynamic resizing is therefore a bit tricky.

Maybe it's possible to define some sort of border/margin around the popup and let android resize it according to the available space, but my knowledge about that is very limited so I can't promise anything so far.

**Comment by opk12** [comment] 2021-07-03 16:17
Is the popup generated by a library? If so, where can I find its issue tracker to do a quick search for an already known issue?

**Comment by opk12** [comment] 2021-07-03 17:22
For example, [OSMBugs](https://github.com/ChristopherGittner/OSMBugs) has round corners and a couple pixel border. The round corners make it apparent that the popup upper edge is not at the right-angled popup border's intersection with the app titlebar.

![screenshot](https://user-images.githubusercontent.com/40740650/124362002-bf3f3c00-dc32-11eb-8997-df02c79c244b.png)

**Comment by hauke96** [comment] 2021-07-03 19:10
OSMBugs and GeoNotes both use [OsmDroid](https://github.com/osmdroid/osmdroid) and both are following the basic strategy: inherit from `InfoWindow`, an abstract class from OsmDroid, and add our own Android-Fragment and logic to it. My own window class is called `MarkerWindow` and can be found [here](https://github.com/hauke96/GeoNotes/blob/main/app/src/main/java/de/hauke_stieler/geonotes/map/MarkerWindow.java).

Feel free to raise an issue at OsmDroid. However I just tried a few things and I think this is not a trivial or even common problem at all.

**Comment by hauke96** [comment] 2021-07-03 23:17
I changed the behavior in 1.4.1 to the following: The upper edge of the popup is not always just below the upper edge of the map. Hopefully this should fix the issue that the popup is not completely visible. The input field is also smaller now and becomes larger when I e.g. add a line break.

I close this issue because the behavior is now fixed. But feel free to re-open it if there's still any problem. The new 1.4.1 version will available in a few days via F-Droid.

**Closed by hauke96** 2021-07-03 23:17 UTC
Labels: bug, good first issue
